<?php
/**
 * Created by PhpStorm.
 * User: palkin
 * Date: 5/16/14
 * Time: 6:31 PM
 */

namespace Acme\EdelaBundle\Form\Type;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class TaskEditFormType extends AbstractType
{

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'task_edit';
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        $builder
            ->add('goal', null, array('required' => false))
            ->add('name', 'text', array('required' => false))
            ->add('date_at', 'date', array('required' => false, 'widget' => 'text', 'format' => 'yyyy-MM-dd'))
            ->add('is_important', null, array('required' => false))
            ->add('is_urgent', null, array('required' => false))
            ->add('is_sms_notification', null, array('required' => false))
            ->add('notification_time', 'time', array('required' => false, 'widget' => 'text'))
            ->add('tags', 'collection', array('required' => false, 'type' => new TagType(), 'allow_add' => true, 'allow_delete' => true, 'delete_empty' => true))
            ->add('note', null, array('required' => false))
            ;
    }


    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults(array(
            'method' => 'PATCH'
        ));
    }

}