parameters:
#    acme_edela.example.class: Acme\EdelaBundle\Example

services:
#    acme_edela.example:
#        class: %acme_edela.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
