<?php

namespace Acme\EdelaBundle\Repository;

use Acme\UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * AchievementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchievementRepository extends EntityRepository
{

    public function getAll(User $user){

        $builder = $this->createQueryBuilder('a');

        $achievements = $builder
            ->select('a.id as id')
            ->addSelect('a.title as title')
            ->addSelect('a.description as description')
            ->addSelect('a.image as image')
            ->addSelect('a.expReward as exp_reward')
            ->addSelect('ua.progress as progress')
            ->leftJoin('AcmeEdelaBundle:UserAchievement', 'ua', Join::WITH, 'ua.achievement=a AND ua.user=:user')
            ->setParameter('user', $user);

        return $achievements->getQuery()->getArrayResult();

    }

}
