<?php

namespace Acme\EdelaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProgressStatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgressStatisticRepository extends EntityRepository
{
}
