<?php

namespace Acme\EdelaBundle\Repository;

use Acme\UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * UserRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRelationRepository extends EntityRepository
{

    public function getRelations(User $user)
    {

        $relations = $this->createQueryBuilder('r');
        $relations->select('friendO as user')
            ->leftJoin('AcmeUserBundle:User', 'friendO', Join::WITH, '( CASE WHEN r.sender=:user THEN IDENTITY(r.receiver) ELSE IDENTITY(r.sender) END )=friendO')
        ;

        $orX = $relations->expr()->orX();
        $orX->add($relations->expr()->eq('r.sender', ':user'));
        $orX->add($relations->expr()->eq('r.receiver', ':user'));

        $relations->andWhere($orX)
            ->setParameter('user', $user);

        $result = $relations->getQuery()->getArrayResult();
        return $result;


    }

}
